{ lib, config, pkgs, ... }:
{
  options = {
    base16-noctalia.enable = lib.mkEnableOption "Enable base16 noctalia dynamic theming";
  };
  config = lib.mkIf config.base16-noctalia.enable {
    extraPlugins = [ pkgs.vimPlugins.base16-nvim ];
    extraConfigLuaPost = ''
      -- Noctalia dynamic theme via base16
      -- Loads ~/.config/nvim/lua/matugen.lua (generated by noctalia template engine)
      -- Falls back to tokyonight if matugen.lua does not exist
      local ok, matugen = pcall(require, 'matugen')
      if ok and matugen.setup then
        matugen.setup()
      end
    '';
  };
}
